"""Dublin Airport (DUB) destinations — April 2026."""

DESTINATIONS = {
    "DUB": {
        "name": "Dublin",
        "routes": {
            # UK
            "ABZ": "Aberdeen",
            "BHX": "Birmingham",
            "BRS": "Bristol",
            "CWL": "Cardiff",
            "EDI": "Edinburgh",
            "EMA": "East Midlands",
            "EXT": "Exeter",
            "GCI": "Guernsey",
            "GLA": "Glasgow",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "JER": "Jersey",
            "LBA": "Leeds Bradford",
            "LCY": "London City",
            "LGW": "London Gatwick",
            "LHR": "London Heathrow",
            "LPL": "Liverpool",
            "LTN": "London Luton",
            "MAN": "Manchester",
            "NCL": "Newcastle",
            "NQY": "Newquay",
            "SOU": "Southampton",
            "STN": "London Stansted",
            # Ireland
            "CFN": "Donegal",
            "KIR": "Kerry",
            # Spain (Mainland)
            "AGP": "Malaga",
            "ALC": "Alicante",
            "BCN": "Barcelona",
            "GRO": "Girona",
            "MAD": "Madrid",
            "OVD": "Asturias",
            "REU": "Reus",
            "RMU": "Murcia",
            "SCQ": "Santiago de Compostela",
            "SDR": "Santander",
            "SVQ": "Seville",
            "VLC": "Valencia",
            # Balearic Islands
            "IBZ": "Ibiza",
            "MAH": "Menorca",
            "PMI": "Palma de Majorca",
            # Canary Islands
            "ACE": "Lanzarote",
            "FUE": "Fuerteventura",
            "LPA": "Gran Canaria",
            "TFS": "Tenerife South",
            # Italy
            "BGY": "Milan Bergamo",
            "BDS": "Brindisi",
            "BLQ": "Bologna",
            "BRI": "Bari",
            "CAG": "Cagliari",
            "CTA": "Catania",
            "FCO": "Rome Fiumicino",
            "LIN": "Milan Linate",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "OLB": "Olbia",
            "PMO": "Palermo",
            "PSA": "Pisa",
            "TRN": "Turin",
            "TRS": "Trieste",
            "VCE": "Venice Marco Polo",
            "VRN": "Verona",
            # France
            "BES": "Brest",
            "BIQ": "Biarritz",
            "BOD": "Bordeaux",
            "BVA": "Paris Beauvais",
            "CCF": "Carcassonne",
            "CDG": "Paris Charles de Gaulle",
            "FNI": "Nimes",
            "GNB": "Grenoble",
            "LDE": "Lourdes",
            "LRH": "La Rochelle",
            "LYS": "Lyon",
            "MPL": "Montpellier",
            "MRS": "Marseille",
            "NCE": "Nice",
            "NTE": "Nantes",
            "ORY": "Paris Orly",
            "PGF": "Perpignan",
            "RNS": "Rennes",
            "TLS": "Toulouse",
            "TUF": "Tours",
            # Germany
            "BER": "Berlin",
            "CGN": "Cologne",
            "DUS": "Dusseldorf",
            "FMM": "Memmingen",
            "FRA": "Frankfurt",
            "HAM": "Hamburg",
            "MUC": "Munich",
            "STR": "Stuttgart",
            # Greece
            "ATH": "Athens",
            "CFU": "Corfu",
            "CHQ": "Chania",
            "HER": "Heraklion",
            "JTR": "Santorini",
            "KGS": "Kos",
            "RHO": "Rhodes",
            "SKG": "Thessaloniki",
            "ZTH": "Zakynthos",
            # Portugal & Azores
            "FAO": "Faro",
            "FNC": "Funchal (Madeira)",
            "LIS": "Lisbon",
            "OPO": "Porto",
            # Turkey
            "ADB": "Izmir",
            "AYT": "Antalya",
            "BJV": "Bodrum",
            "DLM": "Dalaman",
            "IST": "Istanbul",
            "SAW": "Istanbul Sabiha Gokcen",
            # Poland
            "BZG": "Bydgoszcz",
            "GDN": "Gdansk",
            "KRK": "Krakow",
            "KTW": "Katowice",
            "LCJ": "Lodz",
            "LUZ": "Lublin",
            "POZ": "Poznan",
            "RZE": "Rzeszow",
            "SZZ": "Szczecin",
            "WAW": "Warsaw",
            "WMI": "Warsaw Modlin",
            "WRO": "Wroclaw",
            # Romania
            "BCM": "Bacau",
            "CLJ": "Cluj-Napoca",
            "IAS": "Iasi",
            "OTP": "Bucharest",
            # Austria & Switzerland
            "BSL": "Basel",
            "GVA": "Geneva",
            "INN": "Innsbruck",
            "SZG": "Salzburg",
            "VIE": "Vienna",
            "ZRH": "Zurich",
            # Eastern Europe & Balkans
            "BOJ": "Burgas",
            "BTS": "Bratislava",
            "BUD": "Budapest",
            "DBV": "Dubrovnik",
            "KSC": "Kosice",
            "KUN": "Kaunas",
            "PRG": "Prague",
            "RIX": "Riga",
            "RMO": "Chisinau",
            "SOF": "Sofia",
            "SPU": "Split",
            "TIA": "Tirana",
            "TLL": "Tallinn",
            "VNO": "Vilnius",
            "ZAD": "Zadar",
            "ZAG": "Zagreb",
            # Scandinavia & Nordics
            "ARN": "Stockholm",
            "BGO": "Bergen",
            "CPH": "Copenhagen",
            "HEL": "Helsinki",
            "KEF": "Reykjavik",
            "KTT": "Kittila",
            "OSL": "Oslo",
            "RVN": "Rovaniemi",
            "TOS": "Tromso",
            # Benelux & Luxembourg
            "AMS": "Amsterdam",
            "BRU": "Brussels",
            "CRL": "Brussels Charleroi",
            "LUX": "Luxembourg",
            # Cyprus
            "PFO": "Paphos",
            # North Africa
            "AGA": "Agadir",
            "CAI": "Cairo",
            "RAK": "Marrakesh",
            "RBA": "Rabat",
            # Middle East
            "AUH": "Abu Dhabi",
            "DOH": "Doha",
            "DXB": "Dubai",
            # North America (USA)
            "ATL": "Atlanta",
            "BDL": "Hartford",
            "BNA": "Nashville",
            "BOS": "Boston",
            "CLE": "Cleveland",
            "CLT": "Charlotte",
            "CUN": "Cancun",
            "DEN": "Denver",
            "DFW": "Dallas/Fort Worth",
            "DTW": "Detroit",
            "EWR": "Newark",
            "IAD": "Washington Dulles",
            "IND": "Indianapolis",
            "JFK": "New York JFK",
            "LAS": "Las Vegas",
            "LAX": "Los Angeles",
            "MCO": "Orlando",
            "MIA": "Miami",
            "MSP": "Minneapolis",
            "ORD": "Chicago O'Hare",
            "PHL": "Philadelphia",
            "PIT": "Pittsburgh",
            "RDU": "Raleigh-Durham",
            "SEA": "Seattle",
            "SFO": "San Francisco",
            # North America (Canada)
            "YHZ": "Halifax",
            "YUL": "Montreal",
            "YVR": "Vancouver",
            "YYC": "Calgary",
            "YYT": "St Johns",
            "YYZ": "Toronto",
            # Caribbean
            "BGI": "Barbados",
            # Malta
            "MLA": "Malta",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
